### ISSUE TITLE
Please, can anyone explain how can I install this plugin on openSuse Linux?

### ISSUE THREAD

**Issue by joaocarvalhoopen** [mattt-b/odin-mode#9]
Hello,

please, can anyone explain how I install this plugin on openSuse Linux in Doom Emacs.

Best regards,
João Carvalho

**Comment by mattt-b** [comment]
I do not use Doom Emacs, so I'm not really sure how it differs.

I use [straight](https://github.com/raxod502/straight.el) and [use-package](https://github.com/jwiegley/use-package) to install it:
```emacs
;; Not verbatim what I use, since I use flycheck as well, but I think this should work
(use-package odin-mode
  :straight (odin-mode :type git :host github
                       :repo "mattt-b/odin-mode"))
```

Before I used `straight` I just made a local directory for packages and copy/pasted the file into it using [use-package load-path](https://github.com/jwiegley/use-package#extending-the-load-path).

```emacs
(add-to-list 'load-path "~/.emacs.d/local/")
(use-package odin-mode
  :load-path "local/")
```
